language: node_js
node_js:
  - 17

dist: focal

before_install:
   - stty cols 80

addons:
   firefox: latest
   chrome: stable

script:
  - echo ******build starts******
  - echo 'Installing dependencies'
  - npm install
  - echo 'Running tests'
  - cd app
  - npm test