language: node_js
node_js: "stable"

dist: bionic

before_install:
   - stty cols 80

addons:
   firefox: latest
   chrome: stable

script:
  - echo ******build starts******
  - echo 'Installing dependencies'
  - npm install
  - echo 'Running tests'
  - mocha