language: node_js
node_js:
  - 17

dist: focal

before_install:
   - stty cols 80

addons:
   firefox: latest
   chrome: stable

script:
  - npm test

deploy:
   provider: elasticbeanstalk
   access_key_id:
      secure: "$ACCESSKEYID"
   secret_access_key:
      secure: "$SECRETACCESSKEY"
   region: "ap-southeast-1"
   app: "OTOT-B2-app"
   env: "OTOT-B2-environment"
   bucket_name: "OTOT-B2-S3-bucket"